In [4]:
from tcrtrie import VDJdb

In [6]:
df = VDJdb.search( #return pandas.DataFrame
    query="CASSEGTDGYTF",
    maxSubstitution=2,
    maxInsertion=1,
    maxDeletion=1,
    maxEdits=2,
    vGeneFilter="TRBV19*01",
    jGeneFilter="TRBJ1-2*01",
    numThreads=8,
    detailed=True,
)
df

,query,target_index,distance,idx,complex.id,gene,cdr3,v.segm,j.segm,species,...,meta,cdr3fix,web.method,web.method.seq,web.cdr3fix.nc,web.cdr3fix.unmp,vdjdb.pgen.score,alignment_query,alignment_cdr3,alignment_meta
0,CASSEGTDGYTF,71355,2,71355,21271,TRB,CASSEGSYGYTF,TRBV19*01,TRBJ1-2*01,HomoSapiens,...,"{""study.id"": """", ""cell.subset"": """", ""subject.c...","{""cdr3"": ""CASSEGSYGYTF"", ""cdr3_old"": ""CASSEGSY...",sort,singlecell,no,no,3,CASSEGTDGYTF,CASSEGSYGYTF,"{""distance"": 2, ""substitutions"": 2, ""insertion..."
1,CASSEGTDGYTF,55369,2,55369,0,TRB,CASSFGTWGYTF,TRBV19*01,TRBJ1-2*01,HomoSapiens,...,"{""study.id"": """", ""cell.subset"": ""CD8+"", ""subje...","{""cdr3"": ""CASSFGTWGYTF"", ""cdr3_old"": ""CASSFGTW...",sort,amplicon,no,no,2,CASSEGTDGYTF,CASSFGTWGYTF,"{""distance"": 2, ""substitutions"": 2, ""insertion..."
2,CASSEGTDGYTF,1595,2,1595,0,TRB,CASSGTYGYTF,TRBV19*01,TRBJ1-2*01,HomoSapiens,...,"{""study.id"": """", ""cell.subset"": ""CD8+"", ""subje...","{""cdr3"": ""CASSGTYGYTF"", ""cdr3_old"": ""CASSGTYGY...",sort,amplicon,no,no,3,CASSEGTDGYTF,CASS-GTYGYTF,"{""distance"": 2, ""substitutions"": 1, ""insertion..."
3,CASSEGTDGYTF,13272,2,13272,0,TRB,CASSIGTHGYTF,TRBV19*01,TRBJ1-2*01,HomoSapiens,...,"{""study.id"": ""Child_Tcm"", ""cell.subset"": ""CD8+...","{""cdr3"": ""CASSIGTHGYTF"", ""cdr3_old"": ""CASSIGTH...",sort,singlecell,no,no,2,CASSEGTDGYTF,CASSIGTHGYTF,"{""distance"": 2, ""substitutions"": 2, ""insertion..."
4,CASSEGTDGYTF,39777,2,39777,0,TRB,CASSIGTHGYTF,TRBV19*01,TRBJ1-2*01,HomoSapiens,...,"{""study.id"": ""Child"", ""cell.subset"": """", ""subj...","{""cdr3"": ""CASSIGTHGYTF"", ""cdr3_old"": ""CASSIGTH...",sort,singlecell,no,no,2,CASSEGTDGYTF,CASSIGTHGYTF,"{""distance"": 2, ""substitutions"": 2, ""insertion..."
5,CASSEGTDGYTF,12585,2,12585,0,TRB,CASSIGTYGYTF,TRBV19*01,TRBJ1-2*01,HomoSapiens,...,"{""study.id"": ""Child_Tscm"", ""cell.subset"": ""CD8...","{""cdr3"": ""CASSIGTYGYTF"", ""cdr3_old"": ""CASSIGTY...",sort,singlecell,no,no,3,CASSEGTDGYTF,CASSIGTYGYTF,"{""distance"": 2, ""substitutions"": 2, ""insertion..."
6,CASSEGTDGYTF,13759,2,13759,3666,TRB,CASSIGTYGYTF,TRBV19*01,TRBJ1-2*01,HomoSapiens,...,"{""study.id"": ""Adult_Tcm"", ""cell.subset"": ""CD8+...","{""cdr3"": ""CASSIGTYGYTF"", ""cdr3_old"": ""CASSIGTY...",sort,singlecell,no,no,3,CASSEGTDGYTF,CASSIGTYGYTF,"{""distance"": 2, ""substitutions"": 2, ""insertion..."
7,CASSEGTDGYTF,39116,2,39116,0,TRB,CASSIGTYGYTF,TRBV19*01,TRBJ1-2*01,HomoSapiens,...,"{""study.id"": ""Child"", ""cell.subset"": """", ""subj...","{""cdr3"": ""CASSIGTYGYTF"", ""cdr3_old"": ""CASSIGTY...",sort,singlecell,no,no,3,CASSEGTDGYTF,CASSIGTYGYTF,"{""distance"": 2, ""substitutions"": 2, ""insertion..."
8,CASSEGTDGYTF,42525,2,42525,13547,TRB,CASSIGTYGYTF,TRBV19*01,TRBJ1-2*01,HomoSapiens,...,"{""study.id"": ""Child"", ""cell.subset"": ""DAY7_Div...","{""cdr3"": ""CASSIGTYGYTF"", ""cdr3_old"": ""CASSIGTY...",sort,singlecell,no,no,3,CASSEGTDGYTF,CASSIGTYGYTF,"{""distance"": 2, ""substitutions"": 2, ""insertion..."
9,CASSEGTDGYTF,42738,2,42738,0,TRB,CASSIGTYGYTF,TRBV19*01,TRBJ1-2*01,HomoSapiens,...,"{""study.id"": ""Child"", ""cell.subset"": ""DAY5_Div...","{""cdr3"": ""CASSIGTYGYTF"", ""cdr3_old"": ""CASSIGTY...",sort,singlecell,no,no,3,CASSEGTDGYTF,CASSIGTYGYTF,"{""distance"": 2, ""substitutions"": 2, ""insertion..."
10,CASSEGTDGYTF,54897,2,54897,0,TRB,CASSIGTYGYTF,TRBV19*01,TRBJ1-2*01,HomoSapiens,...,"{""study.id"": """", ""cell.subset"": ""CD8+"", ""subje...","{""cdr3"": ""CASSIGTYGYTF"", ""cdr3_old"": ""CASSIGTY...",sort,amplicon,no,no,3,CASSEGTDGYTF,CASSIGTYGYTF,"{""distance"": 2, ""substitutions"": 2, ""insertion..."
11,CASSEGTDGYTF,82707,2,82707,26947,TRB,CASSMGDGYTF,TRBV19*01,TRBJ1-2*01,HomoSapiens,...,"{""study.id"": """", ""cell.subset"": """", ""subject.c...","{""cdr3"": ""CASSMGDGYTF"", ""cdr3_old"": ""CASSMGDGY...",sort,singlecell,no,no,3,CASSEGTDGYTF,CASSMG-DGYTF,"{""distance"": 2, ""substitutions"": 1, ""insertion..."
12,CASSEGTDGYTF,41010,2,41010,0,TRB,CASSVGTYGYTF,TRBV19*01,TRBJ1-2*01,HomoSapiens,...,"{""study.id"": ""Newborn"", ""cell.subset"": ""DAY10_...","{""cdr3"": ""CASSVGTYGYTF"", ""cdr3_old"": ""CASSVGTY...",sort,singlecell,no,no,3,CASSEGTDGYTF,CASSVGTYGYTF,"{""distance"": 2, ""substitutions"": 2, ""insertion..."
13,CASSEGTDGYTF,41031,2,41031,0,TRB,CASSVGTYGYTF,TRBV19*01,TRBJ1-2*01,HomoSapiens,...,"{""study.id"": ""Newborn"", ""cell.subset"": ""DAY10_...","{""cdr3"": ""CASSVGTYGYTF"", ""cdr3_old"": ""CASSVGTY...",sort,singlecell,no,no,3,CASSEGTDGYTF,CASSVGTYGYTF,"{""distance"": 2, ""substitutions"": 2, ""insertion..."

In [9]:
VDJdb.searchForAll(
    queries=["CASSEGTDGYTF", "CAISTGDSNQPQHF"],
    maxSubstitution=2,
    maxInsertion=1,
    maxDeletion=1,
    maxEdits=2,
    vGeneFilters=["TRBV19*01", "TRBV6-6*01"],
    jGeneFilters=["TRBJ1-2*01", "TRBJ1-5*01"],
    numThreads=8,
    detailed=True,
)

,query_index,query,target_index,distance,idx,complex.id,gene,cdr3,v.segm,j.segm,...,meta,cdr3fix,web.method,web.method.seq,web.cdr3fix.nc,web.cdr3fix.unmp,vdjdb.pgen.score,alignment_query,alignment_cdr3,alignment_meta
0,0,CASSEGTDGYTF,71355,2,71355,21271,TRB,CASSEGSYGYTF,TRBV19*01,TRBJ1-2*01,...,"{""study.id"": """", ""cell.subset"": """", ""subject.c...","{""cdr3"": ""CASSEGSYGYTF"", ""cdr3_old"": ""CASSEGSY...",sort,singlecell,no,no,3,CASSEGTDGYTF,CASSEGSYGYTF,"{""distance"": 2, ""substitutions"": 2, ""insertion..."
1,0,CASSEGTDGYTF,55369,2,55369,0,TRB,CASSFGTWGYTF,TRBV19*01,TRBJ1-2*01,...,"{""study.id"": """", ""cell.subset"": ""CD8+"", ""subje...","{""cdr3"": ""CASSFGTWGYTF"", ""cdr3_old"": ""CASSFGTW...",sort,amplicon,no,no,2,CASSEGTDGYTF,CASSFGTWGYTF,"{""distance"": 2, ""substitutions"": 2, ""insertion..."
2,0,CASSEGTDGYTF,1595,2,1595,0,TRB,CASSGTYGYTF,TRBV19*01,TRBJ1-2*01,...,"{""study.id"": """", ""cell.subset"": ""CD8+"", ""subje...","{""cdr3"": ""CASSGTYGYTF"", ""cdr3_old"": ""CASSGTYGY...",sort,amplicon,no,no,3,CASSEGTDGYTF,CASS-GTYGYTF,"{""distance"": 2, ""substitutions"": 1, ""insertion..."
3,0,CASSEGTDGYTF,13272,2,13272,0,TRB,CASSIGTHGYTF,TRBV19*01,TRBJ1-2*01,...,"{""study.id"": ""Child_Tcm"", ""cell.subset"": ""CD8+...","{""cdr3"": ""CASSIGTHGYTF"", ""cdr3_old"": ""CASSIGTH...",sort,singlecell,no,no,2,CASSEGTDGYTF,CASSIGTHGYTF,"{""distance"": 2, ""substitutions"": 2, ""insertion..."
4,0,CASSEGTDGYTF,39777,2,39777,0,TRB,CASSIGTHGYTF,TRBV19*01,TRBJ1-2*01,...,"{""study.id"": ""Child"", ""cell.subset"": """", ""subj...","{""cdr3"": ""CASSIGTHGYTF"", ""cdr3_old"": ""CASSIGTH...",sort,singlecell,no,no,2,CASSEGTDGYTF,CASSIGTHGYTF,"{""distance"": 2, ""substitutions"": 2, ""insertion..."
5,0,CASSEGTDGYTF,12585,2,12585,0,TRB,CASSIGTYGYTF,TRBV19*01,TRBJ1-2*01,...,"{""study.id"": ""Child_Tscm"", ""cell.subset"": ""CD8...","{""cdr3"": ""CASSIGTYGYTF"", ""cdr3_old"": ""CASSIGTY...",sort,singlecell,no,no,3,CASSEGTDGYTF,CASSIGTYGYTF,"{""distance"": 2, ""substitutions"": 2, ""insertion..."
6,0,CASSEGTDGYTF,13759,2,13759,3666,TRB,CASSIGTYGYTF,TRBV19*01,TRBJ1-2*01,...,"{""study.id"": ""Adult_Tcm"", ""cell.subset"": ""CD8+...","{""cdr3"": ""CASSIGTYGYTF"", ""cdr3_old"": ""CASSIGTY...",sort,singlecell,no,no,3,CASSEGTDGYTF,CASSIGTYGYTF,"{""distance"": 2, ""substitutions"": 2, ""insertion..."
7,0,CASSEGTDGYTF,39116,2,39116,0,TRB,CASSIGTYGYTF,TRBV19*01,TRBJ1-2*01,...,"{""study.id"": ""Child"", ""cell.subset"": """", ""subj...","{""cdr3"": ""CASSIGTYGYTF"", ""cdr3_old"": ""CASSIGTY...",sort,singlecell,no,no,3,CASSEGTDGYTF,CASSIGTYGYTF,"{""distance"": 2, ""substitutions"": 2, ""insertion..."
8,0,CASSEGTDGYTF,42525,2,42525,13547,TRB,CASSIGTYGYTF,TRBV19*01,TRBJ1-2*01,...,"{""study.id"": ""Child"", ""cell.subset"": ""DAY7_Div...","{""cdr3"": ""CASSIGTYGYTF"", ""cdr3_old"": ""CASSIGTY...",sort,singlecell,no,no,3,CASSEGTDGYTF,CASSIGTYGYTF,"{""distance"": 2, ""substitutions"": 2, ""insertion..."
9,0,CASSEGTDGYTF,42738,2,42738,0,TRB,CASSIGTYGYTF,TRBV19*01,TRBJ1-2*01,...,"{""study.id"": ""Child"", ""cell.subset"": ""DAY5_Div...","{""cdr3"": ""CASSIGTYGYTF"", ""cdr3_old"": ""CASSIGTY...",sort,singlecell,no,no,3,CASSEGTDGYTF,CASSIGTYGYTF,"{""distance"": 2, ""substitutions"": 2, ""insertion..."
10,0,CASSEGTDGYTF,54897,2,54897,0,TRB,CASSIGTYGYTF,TRBV19*01,TRBJ1-2*01,...,"{""study.id"": """", ""cell.subset"": ""CD8+"", ""subje...","{""cdr3"": ""CASSIGTYGYTF"", ""cdr3_old"": ""CASSIGTY...",sort,amplicon,no,no,3,CASSEGTDGYTF,CASSIGTYGYTF,"{""distance"": 2, ""substitutions"": 2, ""insertion..."
11,0,CASSEGTDGYTF,82707,2,82707,26947,TRB,CASSMGDGYTF,TRBV19*01,TRBJ1-2*01,...,"{""study.id"": """", ""cell.subset"": """", ""subject.c...","{""cdr3"": ""CASSMGDGYTF"", ""cdr3_old"": ""CASSMGDGY...",sort,singlecell,no,no,3,CASSEGTDGYTF,CASSMG-DGYTF,"{""distance"": 2, ""substitutions"": 1, ""insertion..."
12,0,CASSEGTDGYTF,41010,2,41010,0,TRB,CASSVGTYGYTF,TRBV19*01,TRBJ1-2*01,...,"{""study.id"": ""Newborn"", ""cell.subset"": ""DAY10_...","{""cdr3"": ""CASSVGTYGYTF"", ""cdr3_old"": ""CASSVGTY...",sort,singlecell,no,no,3,CASSEGTDGYTF,CASSVGTYGYTF,"{""distance"": 2, ""substitutions"": 2, ""insertion..."
13,0,CASSEGTDGYTF,41031,2,41031,0,TRB,CASSVGTYGYTF,TRBV19*01,TRBJ1-2*01,...,"{""study.id"": ""Newborn"", ""cell.subset"": ""DAY10_...","{""cdr3"": ""CASSVGTYGYTF"", ""cdr3_old"": ""CASSVGTY...",sort,singlecell,no,no,3,CASSEGTDGYTF,CASSVGTYGYTF,"{""distance"": 2, ""substitutions"": 2, ""insertion..."
14,1,CAISTGDSNQPQHF,240,0,240,0,TRB,CAISTGDSNQPQHF,TRBV6-6*01,TRBJ1-5*01,...,"{""study.id"": """", ""cell.subset"": ""CD8+"", ""subje...","{""cdr3"": ""CAISTGDSNQPQHF"", ""cdr3_old"": ""CAISTG...",sort,amplicon,no,no,2,CAISTGDSNQPQHF,CAISTGDSNQPQHF,"{""distance"": 0, ""substitutions"": 0, ""insertion..."
15,1,CAISTGDSNQPQHF,63637,2,63637,17412,TRB,CASNTGDSNQPQHF,TRBV6-6*01,TRBJ1-5*01,...,"{""study.id"": """", ""cell.subset"": """", ""subject.c...","{""cdr3"": ""CASNTGDSNQPQHF"", ""cdr3_old"": ""CASNTG...",sort,singlecell,no,no,2,CAISTGDSNQPQHF,CASNTGDSNQPQHF,"{""distance"": 2, ""substitutions"": 2, ""insertion..."
16,1,CAISTGDSNQPQHF,238,2,238,0,TRB,CASSTGDHSNQPQHF,TRBV6-6*01,TRBJ1-5*01,...,"{""study.id"": """", ""cell.subset"": ""CD8+"", ""subje...","{""cdr3"": ""CASSTGDHSNQPQHF"", ""cdr3_old"": ""CASST...",sort,amplicon,no,no,2,CAISTGD-SNQPQHF,CASSTGDHSNQPQHF,"{""distance"": 2, ""substitutions"": 1, ""insertion..."

In [15]:
VDJdb.searchWithMatrix(
    query="CASSEGTDGYTF",
    maxCost=12,
    detailed=True,
)

,query,target_index,cost,idx,complex.id,gene,cdr3,v.segm,j.segm,species,...,meta,cdr3fix,web.method,web.method.seq,web.cdr3fix.nc,web.cdr3fix.unmp,vdjdb.pgen.score,alignment_query,alignment_cdr3,alignment_meta
0,CASSEGTDGYTF,36919,12.0,36919,0,TRB,CASSEGPSGYTF,TRBV9*01,TRBJ1-2*01,HomoSapiens,...,"{""study.id"": """", ""cell.subset"": ""CD8+"", ""subje...","{""cdr3"": ""CASSEGPSGYTF"", ""cdr3_old"": ""CASSEGPS...",sort,sanger,no,no,2,CASSEGTDGYTF,CASSEGPSGYTF,"{""distance"": 12, ""substitutions"": 2, ""insertio..."
1,CASSEGTDGYTF,99885,0.0,99885,35536,TRB,CASSEGTDGYTF,TRBV4-1*01,TRBJ1-2*01,HomoSapiens,...,"{""study.id"": """", ""cell.subset"": """", ""subject.c...","{""cdr3"": ""CASSEGTDGYTF"", ""cdr3_old"": ""CASSEGTD...",sort,singlecell,no,no,3,CASSEGTDGYTF,CASSEGTDGYTF,"{""distance"": 0, ""substitutions"": 0, ""insertion..."
2,CASSEGTDGYTF,197411,11.5,197411,79083,TRB,CASSEGTDYGYTF,TRBV6-1*01,TRBJ1-2*01,HomoSapiens,...,"{""study.id"": """", ""cell.subset"": ""CD8+"", ""subje...","{""cdr3"": ""CASSEGTDYGYTF"", ""cdr3_old"": ""CASSEGT...",culture,singlecell,no,no,3,CASSEGTD-GYTF,CASSEGTDYGYTF,"{""distance"": 11.5, ""substitutions"": 0, ""insert..."
3,CASSEGTDGYTF,50267,11.5,50267,0,TRB,CASSHGTSGYTF,TRBV4-2*01,TRBJ1-2*01,HomoSapiens,...,"{""study.id"": """", ""cell.subset"": ""CD8+"", ""subje...","{""cdr3"": ""CASSHGTSGYTF"", ""cdr3_old"": ""CASSHGTS...",sort,amplicon,no,no,2,CASSEGTDGYTF,CASSHGTSGYTF,"{""distance"": 11.5, ""substitutions"": 2, ""insert..."
4,CASSEGTDGYTF,79681,10.5,79681,25434,TRB,CASSQGGDGYTF,TRBV4-1*01,TRBJ1-2*01,HomoSapiens,...,"{""study.id"": """", ""cell.subset"": """", ""subject.c...","{""cdr3"": ""CASSQGGDGYTF"", ""cdr3_old"": ""CASSQGGD...",sort,singlecell,no,no,3,CASSEGTDGYTF,CASSQGGDGYTF,"{""distance"": 10.5, ""substitutions"": 2, ""insert..."
5,CASSEGTDGYTF,59325,11.0,59325,15399,TRB,CASSWGTDGYTF,TRBV11-2*01,TRBJ1-2*01,HomoSapiens,...,"{""study.id"": """", ""cell.subset"": ""CD8+"", ""subje...","{""cdr3"": ""CASSWGTDGYTF"", ""cdr3_old"": ""CASSWGTD...",sort,singlecell,no,no,3,CASSEGTDGYTF,CASSWGTDGYTF,"{""distance"": 11, ""substitutions"": 1, ""insertio..."